### ISSUE TITLE
Ardougne Rooftops

### ISSUE THREAD

**Issue by Z7-z** [powerus117/RLAfkMarksCanafis#3]
Is there any reason why you haven't included Ardy Rooftops aswell since they provide more xp so there isn't a reason to do Canifis if you can do Ardy, it would be amazing if this worked for the Ardy course too

**Comment by powerus117** [comment]
Mostly because this hasn't really been requested before and because I cannot test it (I am 80 agi). When I hit 85 at some point, I will add this feature

**Comment by Joeytje50** [comment]
I would like to add to this: please add the exact same feature for _all_ rooftop courses. While no course is as efficient as Canifis for marks of grade, I'd still love to know if it'd be better to wait 5 seconds before jumping off. Just having a timer running in the exact same way as for Canifis, would help a lot for all other courses as well. It would be very well appreciated!

**Comment by powerus117** [comment]
Thanks for the suggestion, it is a bit of an undertaking to support all courses, especially with some special mechanics for some, but I will be looking into this when I get some time (and my agi level allows all courses)

**Comment by TomBMNA** [comment]
Implemented all other rooftops that have marks of grace, currently on PR here https://github.com/runelite/plugin-hub/pull/6581
If u notice any issues after merge, let me know.

**Comment by powerus117** [comment]
Implemented all other rooftops that spawn marks of grace, currently on PR here https://github.com/runelite/plugin-hub/pull/6581
If you notice any issue after merge, let me know.

**Comment by powerus117** [comment]
All rooftops should now be implemented including the ardougne, settings are available to use the elite diary. If anything doesn't work, let me know by opening another issue, thanks for the feedback

**Comment by Z7-z** [comment]
thank you!!
