### ISSUE TITLE
Clarify usage of system time

### ISSUE THREAD

**Issue by albinahlback** [powerus117/RLAfkMarksCanafis#4]
I don't think a small note at the end of the plugin site is sufficient to warn the user about system time. It should be one of the first things that should be mentioned in the section "How to use", or have its own header.

I thought I consistently had bad luck.

**Comment by powerus117** [comment]
I am looking into fixing this automatically so that this should no longer be an issue, but some extra data to verify this will fix it would be great. So could you confirm that syncing your PC's time fixed the issue for you?

**Comment by albinahlback** [comment]
Correct!

**Comment by powerus117** [comment]
Fixed the issue by implementing a NTP client and removed the note from the description. Currently on PR with a bunch of other additions here https://github.com/runelite/plugin-hub/pull/6581
If you notice any issue after merge, let me know

**Comment by powerus117** [comment]
Issue should now be fixed with NTP syncing. If you encounter any issues, feel free to open another issue
