### ISSUE TITLE
A suggestion and a bunch of praise, maybe a conspiracy theory

### ISSUE THREAD

**Issue by Coolgat3** [powerus117/RLAfkMarksCanafis#5]
AMAZING plugin I love it so much, after I lost my first graceful cape because of dumb choices (thank god I didn't decide to slave for the entire set right away), your plugin convinced me to not quit for a few days! Thank you thank you thank you!

My suggestion: Add an option for an audio que if it's possible, i'd love to have your plugin call for more attention when the wait timer runs out

On another note: Doesn't your plugin actually prove that the information on the wiki is false???
I am speaking about the info that presumably the timers take the lap time from your last lap and add it ontop.
The issue is i've done 8 runs in a row, but only when the marks were supposed to spawn according to your plugin, none of them had the wait timer go lower than 1:20 or higher than 2:50, in all 7 out of 8 of them i've found the mark.. At each of them save for the 6th where i didn't find the mark, i have waited at least 1 minute, much more often 2 and a few seconds. Doing the math, it's impossible for the course to be adding the lap time ontop of the base cooldown, assuming the base cooldown really is 2-3 minutes as the wiki says. Just wanna hear your thoughts on this one that's all!

**Comment by powerus117** [comment]
Glad to hear you like the plugin, I appreciate it :)

Thanks for the suggestion, the plugin currently sends a system notification like some other plugins do when the timer is ready. As far as I know, this triggers a sound already which is configurable in RL. Or were u thinking about another type of sound?

About the note, the wiki seems correct to me, maybe u misunderstood the wiki page? It mentions "the cooldown becomes the ending minute of the previous lap plus the cooldown time" which is correct assuming that ending minute means the global minute, so 4:55 is still minute 4. Add 3 minutes and u get that it goes off cooldown on 7:00

**Comment by powerus117** [comment]
I will assume this issue fixed for now as the RL notification settings should handle the sound, if you feel like that's not the case, feel free to re-open this issue
